### ISSUE TITLE
bug: Image render are broken

### ISSUE THREAD

**Issue by troke12** [kyranet/canvas-constructor#375]
**Describe the bug**

The image when we get using `resolveImage` sometimes broken and sometimes normal

The first one (https://a.troke.id/2) **broken**

![first](https://cdn.discordapp.com/attachments/700283326740824086/859988089916620801/unknown.png)

The second one (https://a.troke.id/1) **normal**

![second](https://cdn.discordapp.com/attachments/700283326740824086/859989491317997599/unknown.png)

Code : 
```js
async function createBanner() {
    const img = await resolveImage('./images/banner.png');
    const logo = await resolveImage('https://a.troke.id/1');
    return new Canvas(1920, 436)
        .printImage(img, 0, 0, 1920, 436)
        .setColor('#FFFFFF')
        .setTextFont('72px sans-serif')
        .printText('TROKE', 589, 169)
        .printImage(logo, 296, 101, 128, 128)
        .toBufferAsync();
}
```

**Comment by kyranet** [comment]
The problem here is that https://a.troke.id/2 is a PNG file with bit depth 16, which Cairo seems to not support according to your try.

You can try https://cdn.skyra.pw/skyra-assets/coins_heads.png (which has a bit depth of 8) and you'll see it works.

The only thing I can think of to fix this, is that you can use GIMP or any other image editing tool to export it as a PNG with bit depth 8, then it'll work.

---

Starting with canvas-constructor v5 - which I hope to get ready for next week - you'll be able to use an alternative render engine which does support bit depth 16 (and presumably 24 as well).

**Comment by troke12** [comment]
![image](https://user-images.githubusercontent.com/10250068/124094367-4ea9eb00-da8b-11eb-9f4c-5626a4c8ff91.png)

ah i see, i try it and it's worked, seems like i need to refactor again my avatar server, thank you very much!

**Comment by kyranet** [comment]
Glad I could help!

For future reference, I used https://www.metadata2go.com to read the PNG's metadata, since I don't have my local tool around :)
